apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: webhook
subjects:
  - kind: ServiceAccount
    name: {{ include "matrixinfer.name" . }}-webhook
    namespace: {{ .Release.Namespace }}
