{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
{{- end }}
