/*
Copyright MatrixInfer-AI Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	applyconfigurationmodelv1alpha1 "matrixinfer.ai/matrixinfer/client-go/applyconfiguration/model/v1alpha1"
	scheme "matrixinfer.ai/matrixinfer/client-go/clientset/versioned/scheme"
	modelv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/model/v1alpha1"
)

// AutoscalingPoliciesGetter has a method to return a AutoscalingPolicyInterface.
// A group's client should implement this interface.
type AutoscalingPoliciesGetter interface {
	AutoscalingPolicies(namespace string) AutoscalingPolicyInterface
}

// AutoscalingPolicyInterface has methods to work with AutoscalingPolicy resources.
type AutoscalingPolicyInterface interface {
	Create(ctx context.Context, autoscalingPolicy *modelv1alpha1.AutoscalingPolicy, opts v1.CreateOptions) (*modelv1alpha1.AutoscalingPolicy, error)
	Update(ctx context.Context, autoscalingPolicy *modelv1alpha1.AutoscalingPolicy, opts v1.UpdateOptions) (*modelv1alpha1.AutoscalingPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, autoscalingPolicy *modelv1alpha1.AutoscalingPolicy, opts v1.UpdateOptions) (*modelv1alpha1.AutoscalingPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*modelv1alpha1.AutoscalingPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*modelv1alpha1.AutoscalingPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *modelv1alpha1.AutoscalingPolicy, err error)
	Apply(ctx context.Context, autoscalingPolicy *applyconfigurationmodelv1alpha1.AutoscalingPolicyApplyConfiguration, opts v1.ApplyOptions) (result *modelv1alpha1.AutoscalingPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, autoscalingPolicy *applyconfigurationmodelv1alpha1.AutoscalingPolicyApplyConfiguration, opts v1.ApplyOptions) (result *modelv1alpha1.AutoscalingPolicy, err error)
	AutoscalingPolicyExpansion
}

// autoscalingPolicies implements AutoscalingPolicyInterface
type autoscalingPolicies struct {
	*gentype.ClientWithListAndApply[*modelv1alpha1.AutoscalingPolicy, *modelv1alpha1.AutoscalingPolicyList, *applyconfigurationmodelv1alpha1.AutoscalingPolicyApplyConfiguration]
}

// newAutoscalingPolicies returns a AutoscalingPolicies
func newAutoscalingPolicies(c *RegistryV1alpha1Client, namespace string) *autoscalingPolicies {
	return &autoscalingPolicies{
		gentype.NewClientWithListAndApply[*modelv1alpha1.AutoscalingPolicy, *modelv1alpha1.AutoscalingPolicyList, *applyconfigurationmodelv1alpha1.AutoscalingPolicyApplyConfiguration](
			"autoscalingpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *modelv1alpha1.AutoscalingPolicy { return &modelv1alpha1.AutoscalingPolicy{} },
			func() *modelv1alpha1.AutoscalingPolicyList { return &modelv1alpha1.AutoscalingPolicyList{} },
		),
	}
}
