changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    # If PR has multiple labels, it will be added to the first matching category
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
        - feature
    - title: Bug fixes 🐛
      labels:
        - bug
    - title: Documentation Updates 📚
      labels:
        - documentation
    - title: Other Changes 🔄
      labels:
        - "*"