/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// AutoscalingPolicyBindingSpecApplyConfiguration represents a declarative configuration of the AutoscalingPolicyBindingSpec type for use
// with apply.
type AutoscalingPolicyBindingSpecApplyConfiguration struct {
	PolicyRef     *v1.LocalObjectReference         `json:"policyRef,omitempty"`
	Heterogeneous *HeterogeneousApplyConfiguration `json:"heterogeneous,omitempty"`
	Homogeneous   *HomogeneousApplyConfiguration   `json:"homogeneous,omitempty"`
}

// AutoscalingPolicyBindingSpecApplyConfiguration constructs a declarative configuration of the AutoscalingPolicyBindingSpec type for use with
// apply.
func AutoscalingPolicyBindingSpec() *AutoscalingPolicyBindingSpecApplyConfiguration {
	return &AutoscalingPolicyBindingSpecApplyConfiguration{}
}

// WithPolicyRef sets the PolicyRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PolicyRef field is set to the value of the last call.
func (b *AutoscalingPolicyBindingSpecApplyConfiguration) WithPolicyRef(value v1.LocalObjectReference) *AutoscalingPolicyBindingSpecApplyConfiguration {
	b.PolicyRef = &value
	return b
}

// WithHeterogeneous sets the Heterogeneous field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Heterogeneous field is set to the value of the last call.
func (b *AutoscalingPolicyBindingSpecApplyConfiguration) WithHeterogeneous(value *HeterogeneousApplyConfiguration) *AutoscalingPolicyBindingSpecApplyConfiguration {
	b.Heterogeneous = value
	return b
}

// WithHomogeneous sets the Homogeneous field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Homogeneous field is set to the value of the last call.
func (b *AutoscalingPolicyBindingSpecApplyConfiguration) WithHomogeneous(value *HomogeneousApplyConfiguration) *AutoscalingPolicyBindingSpecApplyConfiguration {
	b.Homogeneous = value
	return b
}
