apiVersion: v1
kind: Service
metadata:
  name: registry-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: registry-webhook
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  ports:
    - port: 443
      targetPort: 8443
      name: https
  selector:
    app.kubernetes.io/instance: registry-webhook
    {{- include "matrixinfer.selectorLabels" . | nindent 4 }}