apiVersion: v1
kind: Namespace
metadata:
  name: matrixinfer-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: model-webhook
  namespace: matrixinfer-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-webhook
  namespace: matrixinfer-system
  labels:
    app: model-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: model-webhook
  template:
    metadata:
      labels:
        app: model-webhook
    spec:
      containers:
      - name: webhook
        image: model-webhook:latest
        imagePullPolicy: IfNotPresent
        args:
        - --port=8443
        - --tls-cert-file=/etc/webhook/certs/tls.crt
        - --tls-private-key-file=/etc/webhook/certs/tls.key
        - --webhook-timeout=30
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8443
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: webhook-certs
        secret:
          secretName: model-webhook-certs