apiVersion: registry.matrixinfer.ai/v1alpha1
kind: Model
metadata:
  annotations:
    api.kubernetes.io/name: example
  name: qwen25
spec:
  name: qwen25-coder-32b
  owner: example
  backends:
    - name: "qwen25-coder-32b-server"
      type: "vLLM"
      modelURI: s3://matrixinfer/Qwen/Qwen2.5-Coder-32B-Instruct
      cacheURI: hostpath:///cache/
      minReplicas: 1
      maxReplicas: 2
      workers:
        - type: server
          image: openeuler/vllm-ascend:latest
          replicase: 1
          pods: 1
          resources:
            limits:
              cpu: "8"
              memory: 96Gi
              huawei.com/ascend-1980: "2"
            requests:
              cpu: "1"
              memory: 96Gi
              huawei.com/ascend-1980: "2"
