apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler
rules:
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - autoscalingpolicybindings
      - autoscalingpolicies
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - autoscalingpolicies/status
      - autoscalingpolicybindings/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - modelservings
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - workload.serving.volcano.sh
    resources:
      - modelservings/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
