# Disable CPU offloading since we're using NIXL for transfer
local_cpu: False
max_local_cpu_ size: 0
max_local _disk size: 0
remote_serde: NULL

# NIXL configuration for KV cache transfer

enable_nixl: True
nixl_role: "sender" # Prefiller acts as KV cache sender
nixl_receiver_host: "localhost" # Host where decoder is running
nixl_receiver port:55555 # Port where decoder is listening
nixl_buffer_size: 1073741824 # 1GB buffer for KV cache transfer
nixl_buffer_device: "cuda" # Use GPu memory for buffer
nixl enable_gc: True # Enable garbage collection
