/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationworkloadv1alpha1 "github.com/volcano-sh/kthena/client-go/applyconfiguration/workload/v1alpha1"
	scheme "github.com/volcano-sh/kthena/client-go/clientset/versioned/scheme"
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// AutoscalingPolicyBindingsGetter has a method to return a AutoscalingPolicyBindingInterface.
// A group's client should implement this interface.
type AutoscalingPolicyBindingsGetter interface {
	AutoscalingPolicyBindings(namespace string) AutoscalingPolicyBindingInterface
}

// AutoscalingPolicyBindingInterface has methods to work with AutoscalingPolicyBinding resources.
type AutoscalingPolicyBindingInterface interface {
	Create(ctx context.Context, autoscalingPolicyBinding *workloadv1alpha1.AutoscalingPolicyBinding, opts v1.CreateOptions) (*workloadv1alpha1.AutoscalingPolicyBinding, error)
	Update(ctx context.Context, autoscalingPolicyBinding *workloadv1alpha1.AutoscalingPolicyBinding, opts v1.UpdateOptions) (*workloadv1alpha1.AutoscalingPolicyBinding, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, autoscalingPolicyBinding *workloadv1alpha1.AutoscalingPolicyBinding, opts v1.UpdateOptions) (*workloadv1alpha1.AutoscalingPolicyBinding, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadv1alpha1.AutoscalingPolicyBinding, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadv1alpha1.AutoscalingPolicyBindingList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadv1alpha1.AutoscalingPolicyBinding, err error)
	Apply(ctx context.Context, autoscalingPolicyBinding *applyconfigurationworkloadv1alpha1.AutoscalingPolicyBindingApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.AutoscalingPolicyBinding, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, autoscalingPolicyBinding *applyconfigurationworkloadv1alpha1.AutoscalingPolicyBindingApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.AutoscalingPolicyBinding, err error)
	AutoscalingPolicyBindingExpansion
}

// autoscalingPolicyBindings implements AutoscalingPolicyBindingInterface
type autoscalingPolicyBindings struct {
	*gentype.ClientWithListAndApply[*workloadv1alpha1.AutoscalingPolicyBinding, *workloadv1alpha1.AutoscalingPolicyBindingList, *applyconfigurationworkloadv1alpha1.AutoscalingPolicyBindingApplyConfiguration]
}

// newAutoscalingPolicyBindings returns a AutoscalingPolicyBindings
func newAutoscalingPolicyBindings(c *WorkloadV1alpha1Client, namespace string) *autoscalingPolicyBindings {
	return &autoscalingPolicyBindings{
		gentype.NewClientWithListAndApply[*workloadv1alpha1.AutoscalingPolicyBinding, *workloadv1alpha1.AutoscalingPolicyBindingList, *applyconfigurationworkloadv1alpha1.AutoscalingPolicyBindingApplyConfiguration](
			"autoscalingpolicybindings",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadv1alpha1.AutoscalingPolicyBinding { return &workloadv1alpha1.AutoscalingPolicyBinding{} },
			func() *workloadv1alpha1.AutoscalingPolicyBindingList {
				return &workloadv1alpha1.AutoscalingPolicyBindingList{}
			},
		),
	}
}
