/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationworkloadv1alpha1 "github.com/volcano-sh/kthena/client-go/applyconfiguration/workload/v1alpha1"
	scheme "github.com/volcano-sh/kthena/client-go/clientset/versioned/scheme"
	workloadv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/workload/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModelInfersGetter has a method to return a ModelInferInterface.
// A group's client should implement this interface.
type ModelInfersGetter interface {
	ModelInfers(namespace string) ModelInferInterface
}

// ModelInferInterface has methods to work with ModelInfer resources.
type ModelInferInterface interface {
	Create(ctx context.Context, modelInfer *workloadv1alpha1.ModelInfer, opts v1.CreateOptions) (*workloadv1alpha1.ModelInfer, error)
	Update(ctx context.Context, modelInfer *workloadv1alpha1.ModelInfer, opts v1.UpdateOptions) (*workloadv1alpha1.ModelInfer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelInfer *workloadv1alpha1.ModelInfer, opts v1.UpdateOptions) (*workloadv1alpha1.ModelInfer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*workloadv1alpha1.ModelInfer, error)
	List(ctx context.Context, opts v1.ListOptions) (*workloadv1alpha1.ModelInferList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *workloadv1alpha1.ModelInfer, err error)
	Apply(ctx context.Context, modelInfer *applyconfigurationworkloadv1alpha1.ModelInferApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.ModelInfer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, modelInfer *applyconfigurationworkloadv1alpha1.ModelInferApplyConfiguration, opts v1.ApplyOptions) (result *workloadv1alpha1.ModelInfer, err error)
	ModelInferExpansion
}

// modelInfers implements ModelInferInterface
type modelInfers struct {
	*gentype.ClientWithListAndApply[*workloadv1alpha1.ModelInfer, *workloadv1alpha1.ModelInferList, *applyconfigurationworkloadv1alpha1.ModelInferApplyConfiguration]
}

// newModelInfers returns a ModelInfers
func newModelInfers(c *WorkloadV1alpha1Client, namespace string) *modelInfers {
	return &modelInfers{
		gentype.NewClientWithListAndApply[*workloadv1alpha1.ModelInfer, *workloadv1alpha1.ModelInferList, *applyconfigurationworkloadv1alpha1.ModelInferApplyConfiguration](
			"modelinfers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *workloadv1alpha1.ModelInfer { return &workloadv1alpha1.ModelInfer{} },
			func() *workloadv1alpha1.ModelInferList { return &workloadv1alpha1.ModelInferList{} },
		),
	}
}
