/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// AutoscalingPolicyListerExpansion allows custom methods to be added to
// AutoscalingPolicyLister.
type AutoscalingPolicyListerExpansion interface{}

// AutoscalingPolicyNamespaceListerExpansion allows custom methods to be added to
// AutoscalingPolicyNamespaceLister.
type AutoscalingPolicyNamespaceListerExpansion interface{}

// AutoscalingPolicyBindingListerExpansion allows custom methods to be added to
// AutoscalingPolicyBindingLister.
type AutoscalingPolicyBindingListerExpansion interface{}

// AutoscalingPolicyBindingNamespaceListerExpansion allows custom methods to be added to
// AutoscalingPolicyBindingNamespaceLister.
type AutoscalingPolicyBindingNamespaceListerExpansion interface{}

// ModelListerExpansion allows custom methods to be added to
// ModelLister.
type ModelListerExpansion interface{}

// ModelNamespaceListerExpansion allows custom methods to be added to
// ModelNamespaceLister.
type ModelNamespaceListerExpansion interface{}

// ModelInferListerExpansion allows custom methods to be added to
// ModelInferLister.
type ModelInferListerExpansion interface{}

// ModelInferNamespaceListerExpansion allows custom methods to be added to
// ModelInferNamespaceLister.
type ModelInferNamespaceListerExpansion interface{}
