/*
Copyright MatrixInfer-AI Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	workloadv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/workload/v1alpha1"
)

// ModelInferLister helps list ModelInfers.
// All objects returned here must be treated as read-only.
type ModelInferLister interface {
	// List lists all ModelInfers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadv1alpha1.ModelInfer, err error)
	// ModelInfers returns an object that can list and get ModelInfers.
	ModelInfers(namespace string) ModelInferNamespaceLister
	ModelInferListerExpansion
}

// modelInferLister implements the ModelInferLister interface.
type modelInferLister struct {
	listers.ResourceIndexer[*workloadv1alpha1.ModelInfer]
}

// NewModelInferLister returns a new ModelInferLister.
func NewModelInferLister(indexer cache.Indexer) ModelInferLister {
	return &modelInferLister{listers.New[*workloadv1alpha1.ModelInfer](indexer, workloadv1alpha1.Resource("modelinfer"))}
}

// ModelInfers returns an object that can list and get ModelInfers.
func (s *modelInferLister) ModelInfers(namespace string) ModelInferNamespaceLister {
	return modelInferNamespaceLister{listers.NewNamespaced[*workloadv1alpha1.ModelInfer](s.ResourceIndexer, namespace)}
}

// ModelInferNamespaceLister helps list and get ModelInfers.
// All objects returned here must be treated as read-only.
type ModelInferNamespaceLister interface {
	// List lists all ModelInfers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*workloadv1alpha1.ModelInfer, err error)
	// Get retrieves the ModelInfer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*workloadv1alpha1.ModelInfer, error)
	ModelInferNamespaceListerExpansion
}

// modelInferNamespaceLister implements the ModelInferNamespaceLister
// interface.
type modelInferNamespaceLister struct {
	listers.ResourceIndexer[*workloadv1alpha1.ModelInfer]
}
