/*
Copyright MatrixInfer-AI Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	networkingv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/networking/v1alpha1"
)

// ModelMatchApplyConfiguration represents a declarative configuration of the ModelMatch type for use
// with apply.
type ModelMatchApplyConfiguration struct {
	Headers map[string]*networkingv1alpha1.StringMatch `json:"headers,omitempty"`
	Uri     *StringMatchApplyConfiguration             `json:"uri,omitempty"`
}

// ModelMatchApplyConfiguration constructs a declarative configuration of the ModelMatch type for use with
// apply.
func ModelMatch() *ModelMatchApplyConfiguration {
	return &ModelMatchApplyConfiguration{}
}

// WithHeaders puts the entries into the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Headers field,
// overwriting an existing map entries in Headers field with the same key.
func (b *ModelMatchApplyConfiguration) WithHeaders(entries map[string]*networkingv1alpha1.StringMatch) *ModelMatchApplyConfiguration {
	if b.Headers == nil && len(entries) > 0 {
		b.Headers = make(map[string]*networkingv1alpha1.StringMatch, len(entries))
	}
	for k, v := range entries {
		b.Headers[k] = v
	}
	return b
}

// WithUri sets the Uri field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Uri field is set to the value of the last call.
func (b *ModelMatchApplyConfiguration) WithUri(value *StringMatchApplyConfiguration) *ModelMatchApplyConfiguration {
	b.Uri = value
	return b
}
