apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kthena.name" . }}-infer-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: infer-gateway
    {{- include "kthena.labels" . | nindent 4 }}
