{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kthena.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
    {{- include "kthena.labels" . | nindent 4 }}
{{- end }}
