apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler
rules:
  - apiGroups:
      - registry.matrixinfer.ai
    resources:
      - autoscalingpolicies
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - registry.matrixinfer.ai
    resources:
      - models
    verbs:
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - registry.matrixinfer.ai
    resources:
      - autoscalingpolicies/finalizers
    verbs:
      - update
  - apiGroups:
      - registry.matrixinfer.ai
    resources:
      - autoscalingpolicies/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - workload.matrixinfer.ai
    resources:
      - modelinfers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - workload.matrixinfer.ai
    resources:
      - modelinfers/status
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
