apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: autoscaler
    {{- include "matrixinfer.labels" . | nindent 4 }}
