/*
Copyright MatrixInfer-AI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelBackendStatusApplyConfiguration represents a declarative configuration of the ModelBackendStatus type for use
// with apply.
type ModelBackendStatusApplyConfiguration struct {
	Name     *string `json:"name,omitempty"`
	Hash     *string `json:"hash,omitempty"`
	Replicas *int32  `json:"replicas,omitempty"`
}

// ModelBackendStatusApplyConfiguration constructs a declarative configuration of the ModelBackendStatus type for use with
// apply.
func ModelBackendStatus() *ModelBackendStatusApplyConfiguration {
	return &ModelBackendStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ModelBackendStatusApplyConfiguration) WithName(value string) *ModelBackendStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithHash sets the Hash field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Hash field is set to the value of the last call.
func (b *ModelBackendStatusApplyConfiguration) WithHash(value string) *ModelBackendStatusApplyConfiguration {
	b.Hash = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ModelBackendStatusApplyConfiguration) WithReplicas(value int32) *ModelBackendStatusApplyConfiguration {
	b.Replicas = &value
	return b
}
