/*
Copyright MatrixInfer-AI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	registryv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/registry/v1alpha1"
)

// TargetApplyConfiguration represents a declarative configuration of the Target type for use
// with apply.
type TargetApplyConfiguration struct {
	Name                  *string                                 `json:"name,omitempty"`
	Kind                  *registryv1alpha1.AutoscalingTargetType `json:"kind,omitempty"`
	TargetRef             *v1.LocalObjectReference                `json:"targetRef,omitempty"`
	AdditionalMatchLabels map[string]string                       `json:"additionalMatchLabels,omitempty"`
	MetricFrom            *MetricFromApplyConfiguration           `json:"metricFrom,omitempty"`
}

// TargetApplyConfiguration constructs a declarative configuration of the Target type for use with
// apply.
func Target() *TargetApplyConfiguration {
	return &TargetApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *TargetApplyConfiguration) WithName(value string) *TargetApplyConfiguration {
	b.Name = &value
	return b
}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *TargetApplyConfiguration) WithKind(value registryv1alpha1.AutoscalingTargetType) *TargetApplyConfiguration {
	b.Kind = &value
	return b
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *TargetApplyConfiguration) WithTargetRef(value v1.LocalObjectReference) *TargetApplyConfiguration {
	b.TargetRef = &value
	return b
}

// WithAdditionalMatchLabels puts the entries into the AdditionalMatchLabels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the AdditionalMatchLabels field,
// overwriting an existing map entries in AdditionalMatchLabels field with the same key.
func (b *TargetApplyConfiguration) WithAdditionalMatchLabels(entries map[string]string) *TargetApplyConfiguration {
	if b.AdditionalMatchLabels == nil && len(entries) > 0 {
		b.AdditionalMatchLabels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.AdditionalMatchLabels[k] = v
	}
	return b
}

// WithMetricFrom sets the MetricFrom field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MetricFrom field is set to the value of the last call.
func (b *TargetApplyConfiguration) WithMetricFrom(value *MetricFromApplyConfiguration) *TargetApplyConfiguration {
	b.MetricFrom = value
	return b
}
