/*
Copyright MatrixInfer-AI Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	applyconfigurationregistryv1alpha1 "matrixinfer.ai/matrixinfer/client-go/applyconfiguration/registry/v1alpha1"
	scheme "matrixinfer.ai/matrixinfer/client-go/clientset/versioned/scheme"
	registryv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/registry/v1alpha1"
)

// LoraAdaptersGetter has a method to return a LoraAdapterInterface.
// A group's client should implement this interface.
type LoraAdaptersGetter interface {
	LoraAdapters(namespace string) LoraAdapterInterface
}

// LoraAdapterInterface has methods to work with LoraAdapter resources.
type LoraAdapterInterface interface {
	Create(ctx context.Context, loraAdapter *registryv1alpha1.LoraAdapter, opts v1.CreateOptions) (*registryv1alpha1.LoraAdapter, error)
	Update(ctx context.Context, loraAdapter *registryv1alpha1.LoraAdapter, opts v1.UpdateOptions) (*registryv1alpha1.LoraAdapter, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, loraAdapter *registryv1alpha1.LoraAdapter, opts v1.UpdateOptions) (*registryv1alpha1.LoraAdapter, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*registryv1alpha1.LoraAdapter, error)
	List(ctx context.Context, opts v1.ListOptions) (*registryv1alpha1.LoraAdapterList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *registryv1alpha1.LoraAdapter, err error)
	Apply(ctx context.Context, loraAdapter *applyconfigurationregistryv1alpha1.LoraAdapterApplyConfiguration, opts v1.ApplyOptions) (result *registryv1alpha1.LoraAdapter, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, loraAdapter *applyconfigurationregistryv1alpha1.LoraAdapterApplyConfiguration, opts v1.ApplyOptions) (result *registryv1alpha1.LoraAdapter, err error)
	LoraAdapterExpansion
}

// loraAdapters implements LoraAdapterInterface
type loraAdapters struct {
	*gentype.ClientWithListAndApply[*registryv1alpha1.LoraAdapter, *registryv1alpha1.LoraAdapterList, *applyconfigurationregistryv1alpha1.LoraAdapterApplyConfiguration]
}

// newLoraAdapters returns a LoraAdapters
func newLoraAdapters(c *RegistryV1alpha1Client, namespace string) *loraAdapters {
	return &loraAdapters{
		gentype.NewClientWithListAndApply[*registryv1alpha1.LoraAdapter, *registryv1alpha1.LoraAdapterList, *applyconfigurationregistryv1alpha1.LoraAdapterApplyConfiguration](
			"loraadapters",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *registryv1alpha1.LoraAdapter { return &registryv1alpha1.LoraAdapter{} },
			func() *registryv1alpha1.LoraAdapterList { return &registryv1alpha1.LoraAdapterList{} },
		),
	}
}
