apiVersion: v1
kind: ServiceAccount
metadata:
  name: registry-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: model-controller
    {{- include "matrixinfer.labels" . | nindent 4 }}