apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: webhook
rules:
  - apiGroups:
      - registry.volcano.sh
    resources:
      - autoscalingpolicies
    verbs:
      - get
