apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelBooster
metadata:
  name: deepseek-v2-lite
  namespace: dev
spec:
  name: deepseek-v2-lite
  owner: example
  backends:
    - name: deepseek-v2-lite
      type: vLLMDisaggregated
      modelURI: hf://deepseek-ai/DeepSeek-V2-Lite
      cacheURI: hostpath:///mnt/cache/
      minReplicas: 1
      maxReplicas: 1
      workers:
        - type: prefill
          image: ghcr.io/kthena/kthena-engine:vllm-ascend_v0.10.1rc1_mooncake_v0.3.5
          replicas: 1
          pods: 1
          resources:
            limits:
              cpu: "8"
              memory: 64Gi
              huawei.com/ascend-1980: "4"
            requests:
              cpu: "8"
              memory: 64Gi
              huawei.com/ascend-1980: "4"
          config:
            served-model-name: "deepseek-ai/DeepSeekV2"
            tensor-parallel-size: 2
            max-model-len: 8192
            gpu-memory-utilization: 0.8
            max-num-batched-tokens: 8192
            trust-remote-code: ""
            enforce-eager: ""
            kv-transfer-config: |
              {"kv_connector": "MooncakeConnectorV1",
                "kv_buffer_device": "npu",
                "kv_role": "kv_producer",
                "kv_parallel_size": 1,
                "kv_port": "20001",
                "engine_id": "0",
                "kv_rank": 0,
                "kv_connector_module_path": "vllm_ascend.distributed.mooncake_connector",
                "kv_connector_extra_config": {
                  "prefill": {
                    "dp_size": 2,
                    "tp_size": 2
                  },
                  "decode": {
                    "dp_size": 2,
                    "tp_size": 2
                  }
                }
              }
        - type: decode
          image: ghcr.io/kthena/kthena-engine:vllm-ascend_v0.10.1rc1_mooncake_v0.3.5
          replicas: 1
          pods: 1
          resources:
            limits:
              cpu: "8"
              memory: 64Gi
              huawei.com/ascend-1980: "4"
            requests:
              cpu: "8"
              memory: 64Gi
              huawei.com/ascend-1980: "4"
          config:
            served-model-name: "deepseek-ai/DeepSeekV2"
            tensor-parallel-size: 2
            max-model-len: 8192
            gpu-memory-utilization: 0.8
            max-num-batched-tokens: 16384
            trust-remote-code: ""
            enforce-eager: ""
            kv-transfer-config: |
              {"kv_connector": "MooncakeConnectorV1",
                "kv_buffer_device": "npu",
                "kv_role": "kv_consumer",
                "kv_parallel_size": 1,
                "kv_port": "20002",
                "engine_id": "1",
                "kv_rank": 1,
                "kv_connector_module_path": "vllm_ascend.distributed.mooncake_connector",
                "kv_connector_extra_config": {
                  "prefill": {
                    "dp_size": 2,
                    "tp_size": 2
                  },
                  "decode": {
                    "dp_size": 2,
                    "tp_size": 2
                  }
                }
              }
