/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationnetworkingv1alpha1 "github.com/volcano-sh/kthena/client-go/applyconfiguration/networking/v1alpha1"
	scheme "github.com/volcano-sh/kthena/client-go/clientset/versioned/scheme"
	networkingv1alpha1 "github.com/volcano-sh/kthena/pkg/apis/networking/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ModelRoutesGetter has a method to return a ModelRouteInterface.
// A group's client should implement this interface.
type ModelRoutesGetter interface {
	ModelRoutes(namespace string) ModelRouteInterface
}

// ModelRouteInterface has methods to work with ModelRoute resources.
type ModelRouteInterface interface {
	Create(ctx context.Context, modelRoute *networkingv1alpha1.ModelRoute, opts v1.CreateOptions) (*networkingv1alpha1.ModelRoute, error)
	Update(ctx context.Context, modelRoute *networkingv1alpha1.ModelRoute, opts v1.UpdateOptions) (*networkingv1alpha1.ModelRoute, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelRoute *networkingv1alpha1.ModelRoute, opts v1.UpdateOptions) (*networkingv1alpha1.ModelRoute, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkingv1alpha1.ModelRoute, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkingv1alpha1.ModelRouteList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkingv1alpha1.ModelRoute, err error)
	Apply(ctx context.Context, modelRoute *applyconfigurationnetworkingv1alpha1.ModelRouteApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha1.ModelRoute, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, modelRoute *applyconfigurationnetworkingv1alpha1.ModelRouteApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha1.ModelRoute, err error)
	ModelRouteExpansion
}

// modelRoutes implements ModelRouteInterface
type modelRoutes struct {
	*gentype.ClientWithListAndApply[*networkingv1alpha1.ModelRoute, *networkingv1alpha1.ModelRouteList, *applyconfigurationnetworkingv1alpha1.ModelRouteApplyConfiguration]
}

// newModelRoutes returns a ModelRoutes
func newModelRoutes(c *NetworkingV1alpha1Client, namespace string) *modelRoutes {
	return &modelRoutes{
		gentype.NewClientWithListAndApply[*networkingv1alpha1.ModelRoute, *networkingv1alpha1.ModelRouteList, *applyconfigurationnetworkingv1alpha1.ModelRouteApplyConfiguration](
			"modelroutes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkingv1alpha1.ModelRoute { return &networkingv1alpha1.ModelRoute{} },
			func() *networkingv1alpha1.ModelRouteList { return &networkingv1alpha1.ModelRouteList{} },
		),
	}
}
