/*
Copyright MatrixInfer-AI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	applyconfigurationnetworkingv1alpha1 "matrixinfer.ai/matrixinfer/client-go/applyconfiguration/networking/v1alpha1"
	scheme "matrixinfer.ai/matrixinfer/client-go/clientset/versioned/scheme"
	networkingv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/networking/v1alpha1"
)

// ModelServersGetter has a method to return a ModelServerInterface.
// A group's client should implement this interface.
type ModelServersGetter interface {
	ModelServers(namespace string) ModelServerInterface
}

// ModelServerInterface has methods to work with ModelServer resources.
type ModelServerInterface interface {
	Create(ctx context.Context, modelServer *networkingv1alpha1.ModelServer, opts v1.CreateOptions) (*networkingv1alpha1.ModelServer, error)
	Update(ctx context.Context, modelServer *networkingv1alpha1.ModelServer, opts v1.UpdateOptions) (*networkingv1alpha1.ModelServer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, modelServer *networkingv1alpha1.ModelServer, opts v1.UpdateOptions) (*networkingv1alpha1.ModelServer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*networkingv1alpha1.ModelServer, error)
	List(ctx context.Context, opts v1.ListOptions) (*networkingv1alpha1.ModelServerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *networkingv1alpha1.ModelServer, err error)
	Apply(ctx context.Context, modelServer *applyconfigurationnetworkingv1alpha1.ModelServerApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha1.ModelServer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, modelServer *applyconfigurationnetworkingv1alpha1.ModelServerApplyConfiguration, opts v1.ApplyOptions) (result *networkingv1alpha1.ModelServer, err error)
	ModelServerExpansion
}

// modelServers implements ModelServerInterface
type modelServers struct {
	*gentype.ClientWithListAndApply[*networkingv1alpha1.ModelServer, *networkingv1alpha1.ModelServerList, *applyconfigurationnetworkingv1alpha1.ModelServerApplyConfiguration]
}

// newModelServers returns a ModelServers
func newModelServers(c *NetworkingV1alpha1Client, namespace string) *modelServers {
	return &modelServers{
		gentype.NewClientWithListAndApply[*networkingv1alpha1.ModelServer, *networkingv1alpha1.ModelServerList, *applyconfigurationnetworkingv1alpha1.ModelServerApplyConfiguration](
			"modelservers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *networkingv1alpha1.ModelServer { return &networkingv1alpha1.ModelServer{} },
			func() *networkingv1alpha1.ModelServerList { return &networkingv1alpha1.ModelServerList{} },
		),
	}
}
