{{- if .Values.boosterWebhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kthena.name" . }}-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: webhook
    {{- include "kthena.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.boosterWebhook.replicas | default 1 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: webhook
      {{- include "kthena.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: webhook
        {{- include "kthena.labels" . | nindent 8 }}
    spec:
      containers:
        - name: webhook
          image: "{{ .Values.boosterWebhook.image.repository }}:{{ .Values.boosterWebhook.image.tag }}"
          imagePullPolicy: {{ .Values.boosterWebhook.image.pullPolicy }}
          args: {{- toYaml .Values.boosterWebhook.image.args | nindent 12 }}
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          resources: {{- toYaml .Values.boosterWebhook.resource | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8443
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "kthena.name" . }}-webhook-certs
      serviceAccountName: {{ include "kthena.name" . }}-webhook
{{- end }}
