{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kthena.name" . }}-infer-router-validating-webhook
  labels:
    app.kubernetes.io/component: webhook
    {{- include "kthena.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "kthena.name" . }}-webhook-cert
webhooks:
  - name: validate-networking-volcano-sh-v1alpha1-modelroute.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: {{ include "kthena.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate-modelroute"
        port: 443
      caBundle: ""
    rules:
      - apiGroups: [ "networking.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelroutes" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
  - name: validate-networking-volcano-sh-v1alpha1-modelserver.volcano.sh
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 30
    clientConfig:
      service:
        name: {{ include "kthena.name" . }}-webhook
        namespace: {{ .Release.Namespace }}
        path: "/validate-modelserver"
        port: 443
      caBundle: ""
    rules:
      - apiGroups: [ "networking.volcano.sh" ]
        apiVersions: [ "v1alpha1" ]
        resources: [ "modelservers" ]
        operations: [ "CREATE", "UPDATE" ]
        scope: "Namespaced"
{{- end }}
