apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "matrixinfer.name" . }}-model-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: model-controller
    {{- include "matrixinfer.labels" . | nindent 4 }}
