/*
Copyright MatrixInfer-AI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	registryv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/registry/v1alpha1"
)

// AutoscalingPolicyLister helps list AutoscalingPolicies.
// All objects returned here must be treated as read-only.
type AutoscalingPolicyLister interface {
	// List lists all AutoscalingPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*registryv1alpha1.AutoscalingPolicy, err error)
	// AutoscalingPolicies returns an object that can list and get AutoscalingPolicies.
	AutoscalingPolicies(namespace string) AutoscalingPolicyNamespaceLister
	AutoscalingPolicyListerExpansion
}

// autoscalingPolicyLister implements the AutoscalingPolicyLister interface.
type autoscalingPolicyLister struct {
	listers.ResourceIndexer[*registryv1alpha1.AutoscalingPolicy]
}

// NewAutoscalingPolicyLister returns a new AutoscalingPolicyLister.
func NewAutoscalingPolicyLister(indexer cache.Indexer) AutoscalingPolicyLister {
	return &autoscalingPolicyLister{listers.New[*registryv1alpha1.AutoscalingPolicy](indexer, registryv1alpha1.Resource("autoscalingpolicy"))}
}

// AutoscalingPolicies returns an object that can list and get AutoscalingPolicies.
func (s *autoscalingPolicyLister) AutoscalingPolicies(namespace string) AutoscalingPolicyNamespaceLister {
	return autoscalingPolicyNamespaceLister{listers.NewNamespaced[*registryv1alpha1.AutoscalingPolicy](s.ResourceIndexer, namespace)}
}

// AutoscalingPolicyNamespaceLister helps list and get AutoscalingPolicies.
// All objects returned here must be treated as read-only.
type AutoscalingPolicyNamespaceLister interface {
	// List lists all AutoscalingPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*registryv1alpha1.AutoscalingPolicy, err error)
	// Get retrieves the AutoscalingPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*registryv1alpha1.AutoscalingPolicy, error)
	AutoscalingPolicyNamespaceListerExpansion
}

// autoscalingPolicyNamespaceLister implements the AutoscalingPolicyNamespaceLister
// interface.
type autoscalingPolicyNamespaceLister struct {
	listers.ResourceIndexer[*registryv1alpha1.AutoscalingPolicy]
}
