/*
Copyright MatrixInfer-AI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
	registryv1alpha1 "matrixinfer.ai/matrixinfer/pkg/apis/registry/v1alpha1"
)

// AutoscalingPolicyBindingLister helps list AutoscalingPolicyBindings.
// All objects returned here must be treated as read-only.
type AutoscalingPolicyBindingLister interface {
	// List lists all AutoscalingPolicyBindings in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*registryv1alpha1.AutoscalingPolicyBinding, err error)
	// AutoscalingPolicyBindings returns an object that can list and get AutoscalingPolicyBindings.
	AutoscalingPolicyBindings(namespace string) AutoscalingPolicyBindingNamespaceLister
	AutoscalingPolicyBindingListerExpansion
}

// autoscalingPolicyBindingLister implements the AutoscalingPolicyBindingLister interface.
type autoscalingPolicyBindingLister struct {
	listers.ResourceIndexer[*registryv1alpha1.AutoscalingPolicyBinding]
}

// NewAutoscalingPolicyBindingLister returns a new AutoscalingPolicyBindingLister.
func NewAutoscalingPolicyBindingLister(indexer cache.Indexer) AutoscalingPolicyBindingLister {
	return &autoscalingPolicyBindingLister{listers.New[*registryv1alpha1.AutoscalingPolicyBinding](indexer, registryv1alpha1.Resource("autoscalingpolicybinding"))}
}

// AutoscalingPolicyBindings returns an object that can list and get AutoscalingPolicyBindings.
func (s *autoscalingPolicyBindingLister) AutoscalingPolicyBindings(namespace string) AutoscalingPolicyBindingNamespaceLister {
	return autoscalingPolicyBindingNamespaceLister{listers.NewNamespaced[*registryv1alpha1.AutoscalingPolicyBinding](s.ResourceIndexer, namespace)}
}

// AutoscalingPolicyBindingNamespaceLister helps list and get AutoscalingPolicyBindings.
// All objects returned here must be treated as read-only.
type AutoscalingPolicyBindingNamespaceLister interface {
	// List lists all AutoscalingPolicyBindings in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*registryv1alpha1.AutoscalingPolicyBinding, err error)
	// Get retrieves the AutoscalingPolicyBinding from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*registryv1alpha1.AutoscalingPolicyBinding, error)
	AutoscalingPolicyBindingNamespaceListerExpansion
}

// autoscalingPolicyBindingNamespaceLister implements the AutoscalingPolicyBindingNamespaceLister
// interface.
type autoscalingPolicyBindingNamespaceLister struct {
	listers.ResourceIndexer[*registryv1alpha1.AutoscalingPolicyBinding]
}
