apiVersion: workload.serving.volcano.sh/v1alpha1
kind: ModelServing
metadata: ${MODEL_SERVING_TEMPLATE_METADATA}
spec:
  recoveryPolicy: InferGroupRecreate
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: InferGroupRollingUpdate
  schedulerName: volcano
  replicas: ${BACKEND_REPLICAS}
  template:
    restartGracePeriodSeconds: 60
    roles:
      - name: prefill
        replicas: ${PREFILL_REPLICAS}
        entryTemplate:
          spec:
            initContainers: ${INIT_CONTAINERS}
            containers:
              - name: runtime
                image: ${MODEL_SERVING_RUNTIME_IMAGE}
                ports:
                  - containerPort: ${MODEL_SERVING_RUNTIME_PORT}
                env: ${ENGINE_PREFILL_ENV}
                args:
                  - --port
                  - ${MODEL_SERVING_RUNTIME_PORT}
                  - --engine
                  - ${MODEL_SERVING_RUNTIME_ENGINE}
                  - --engine-base-url
                  - ${MODEL_SERVING_RUNTIME_URL}
                  - --engine-metrics-path
                  - ${MODEL_SERVING_RUNTIME_METRICS_PATH}
                  - --pod
                  - ${MODEL_SERVING_RUNTIME_POD}
                  - --model
                  - ${MODEL_NAME}
              - name: vllm
                image: ${ENGINE_PREFILL_IMAGE}
                ports:
                  - containerPort: 8000
                env: ${ENGINE_PREFILL_ENV}
                command: ${ENGINE_PREFILL_COMMAND}
                imagePullPolicy: IfNotPresent
                resources: ${ENGINE_PREFILL_RESOURCES}
                readinessProbe:
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                livenessProbe:
                  initialDelaySeconds: 90
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                volumeMounts: ${VOLUME_MOUNTS}
            volumes: ${VOLUMES}
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node.kubernetes.io/npu.chip.name
                          operator: In
                          values:
                            - Ascend910
        workerReplicas: 0
        workerTemplate:
          spec:
            containers: []
      - name: decode
        replicas: ${DECODE_REPLICAS}
        entryTemplate:
          spec:
            initContainers: ${INIT_CONTAINERS}
            containers:
              - name: runtime
                image: ${MODEL_SERVING_RUNTIME_IMAGE}
                ports:
                  - containerPort: ${MODEL_SERVING_RUNTIME_PORT}
                env: ${ENGINE_DECODE_ENV}
                envFrom: ${MODEL_DOWNLOAD_ENVFROM}
                args:
                  - --port
                  - ${MODEL_SERVING_RUNTIME_PORT}
                  - --engine
                  - ${MODEL_SERVING_RUNTIME_ENGINE}
                  - --engine-base-url
                  - ${MODEL_SERVING_RUNTIME_URL}
                  - --engine-metrics-path
                  - ${MODEL_SERVING_RUNTIME_METRICS_PATH}
                  - --pod
                  - ${MODEL_SERVING_RUNTIME_POD}
                  - --model
                  - ${MODEL_NAME}
              - name: vllm
                image: ${ENGINE_DECODE_IMAGE}
                ports:
                  - containerPort: 8000
                env: ${ENGINE_DECODE_ENV}
                command: ${ENGINE_DECODE_COMMAND}
                imagePullPolicy: IfNotPresent
                resources: ${ENGINE_DECODE_RESOURCES}
                readinessProbe:
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                livenessProbe:
                  initialDelaySeconds: 90
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                volumeMounts: ${VOLUME_MOUNTS}
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node.kubernetes.io/npu.chip.name
                          operator: In
                          values:
                            - Ascend910
            volumes: ${VOLUMES}
        workerReplicas: 0
        workerTemplate:
          spec:
            containers: []