apiVersion: v1
kind: Namespace
metadata:
  name: matrixinfer-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: infer-controller
  namespace: matrixinfer-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: infer-controller
  namespace: matrixinfer-system
  labels:
    app: infer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infer-controller
  template:
    metadata:
      labels:
        app: infer-controller
    spec:
      containers:
      - name: infer-controller
        image: ghcr.io/matrixinfer-ai/infer-controller:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: infer-controller