---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infer-controller
rules:
- apiGroups:
  - workload.matrixinfer.ai
  resources:
  - modelinfers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.matrixinfer.ai
  resources:
  - modelinfers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - watch
- apiGroups:
    - ""
  resources:
    - services
  verbs:
    - create
    - delete
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infer-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infer-controller
subjects:
- kind: ServiceAccount
  name: infer-controller
  namespace: matrixinfer-system
