apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: modelinfer-validating-webhook
  labels:
    app: modelinfer-webhook
  annotations:
    cert-manager.io/inject-ca-from: matrixinfer-system/modelinfer-webhook-cert
webhooks:
- name: validate-modelinfer-matrixinfer-ai-v1alpha1-modelinfer.matrixinfer.ai
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: Fail
  timeoutSeconds: 30
  clientConfig:
    service:
      name: modelinfer-webhook
      namespace: matrixinfer-system
      path: "/validate-matrixinfer-ai-v1alpha1-modelinfer"
      port: 443
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURpakNDQW5LZ0F3SUJBZ0lVQVVKUjRIcHlSekxWQlpCWExXazNPbnQ4TCtRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd05ERXlNREFHQTFVRUF3d3BiVzlrWld4cGJtWmxjaTEzWldKb2IyOXJMbTFoZEhKcGVHbHVabVZ5TFhONQpjM1JsYlM1emRtTXdIaGNOTWpVd056RTRNRE16TVRRMldoY05Nall3TnpFNE1ETXpNVFEyV2pBME1USXdNQVlEClZRUUREQ2x0YjJSbGJHbHVabVZ5TFhkbFltaHZiMnN1YldGMGNtbDRhVzVtWlhJdGMzbHpkR1Z0TG5OMll6Q0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFJOGlXdnpBVHFWLytXWDRqVjlUN3RRTApDcGRDNkFRTXBZdXpEVHBqL25YcVIvdG92RUpPVm5LOXJHWlB6ZzErZndmTXlEcUNUVnd1Y2w2RGRMQ08rVnVYCm1ldXZMYXlOWkQ5NElFR25MSGJNSWVpNFdEazVCb2NqVFpjcnI2L01lbzE4R2ZLUU5kVDhtQit3RWJjMTlrTXgKV2Z4bXAvM3ZWK213cDJXY2dzRHdBUXN2MW5mdjN2UWgreXIxR3BRSHk2RUhLSElNUDhJU0xxT0ZMWGQvYkpGVgpxNHQ2RVJxQmlJOXZaeEt6RE52dVdGV05jWDJYcFVnTXppZFhVbUE2MW44aWVWSVlGcjdMVituY0dnbGRLZnptCm4rb3lHdW9XUGowbFVkUTBrYWpmSWI1L2FnM1B5dGtUdjlCbnd1R3NIT09pblg5MVJiSVBQUDNycXEwSS9KOEMKQXdFQUFhT0JrekNCa0RCdkJnTlZIUkVFYURCbWdoSnRiMlJsYkdsdVptVnlMWGRsWW1odmIydUNKVzF2WkdWcwphVzVtWlhJdGQyVmlhRzl2YXk1dFlYUnlhWGhwYm1abGNpMXplWE4wWlcyQ0tXMXZaR1ZzYVc1bVpYSXRkMlZpCmFHOXZheTV0WVhSeWFYaHBibVpsY2kxemVYTjBaVzB1YzNaak1CMEdBMVVkRGdRV0JCUzZENHF3TC9LZG50OHYKamt0dXFSWHY1cTFBWmpBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQUo4eFNHNVJ0eG9CYTQydmFtMnBYTEFYYwp2WVowcnNDcUlzdm1mQVR5SjFRcEZqNjlJUHZHUEpKWVRnaUl2UG9IWElzN1VodXRtdXJoNG1qVFM5aE9BOGhECklDMzRNVzZZd29UbXRBSEF1bXdmZ2kvN0tMUkNtcEtFNm5tUmhkUnh0VU5BU1hjTUhRU1FxVlEwTlVxV3JaN0QKejluU29xK2M3UlMxb3JjWlJId21tUkhVSFBQRTcxcTEwSnR0ZHBOQ1diUExFZTRXd01KZE9ZZ1pxdnozUFFBZAozVmxKdXRDYXBta3lCOEpLb3Q1c0VFOWxqZ3ErMXg0cjdkVmpnTFluTEZtYlpNTEw4Y3EwdjF2MFNONTkyczB4CjdCZmptaUpSMGI2VG9ZeGhPaFVYYnZSSllFNWdBakZGRFBEMURsNm5OczdEQnh3aXNwdWFZS0E2N29TQXpnPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  rules:
  - apiGroups: ["workload.matrixinfer.ai"]
    apiVersions: ["v1alpha1"]
    resources: ["modelinfers"]
    operations: ["CREATE", "UPDATE"]
    scope: "Namespaced"
