apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infer-controller
rules:
  - apiGroups:
      - workload.volcano.sh
    resources:
      - modelinfers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - workload.volcano.sh
    resources:
      - modelinfers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - delete
      - get
      - list
      - watch
  - apiGroups:
    - scheduling.volcano.sh
    resources:
    - podgroups
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
