apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: infer-gateway
  labels:
    app.kubernetes.io/component: infer-gateway-role-binding
    {{- include "matrixinfer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: infer-gateway
subjects:
  - kind: ServiceAccount
    name: infer-gateway
    namespace: {{ .Release.Namespace }}
