{{- if .Values.redis.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.redis.namespace }}
  labels:
    name: {{ .Values.redis.namespace }}

---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: {{ .Values.redis.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-server
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.redis.service.type }}
  ports:
    - name: redis-port
      protocol: TCP
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: {{ .Values.redis.namespace }}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-server
    {{- include "matrixinfer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: redis-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: redis-server
        {{- include "matrixinfer.labels" . | nindent 8 }}
    spec:
      containers:
        - name: redis-server
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.redis.image.pullPolicy }}
          command:
            - redis-server
          ports:
            - name: redis-port
              containerPort: {{ .Values.redis.service.port }}
              protocol: TCP
          resources: {{- toYaml .Values.redis.resource | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
{{- end }}