---
apiVersion: v1
kind: Namespace
metadata:
  name: matrixinfer-system
  labels:
    name: matrixinfer-system

---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: matrixinfer-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-server
    app.kubernetes.io/part-of: matrixinfer
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      protocol: TCP
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-server
  namespace: matrixinfer-system
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: redis-server
    app.kubernetes.io/part-of: matrixinfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/component: redis-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/component: redis-server
        app.kubernetes.io/part-of: matrixinfer
    spec:
      containers:
        - name: lookup-server
          image: redis:7.2-alpine
          imagePullPolicy: IfNotPresent
          command:
            - redis-server
          ports:
            - name: redis-port
              containerPort: 6379
              protocol: TCP
          resources:
            limits:
              cpu: '8'
              memory: 30Gi
            requests:
              cpu: '4'
              memory: 8Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600