apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: infer-router
rules:
  - apiGroups:
      - networking.volcano.sh
    resources:
      - modelroutes
      - modelservers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - networking.volcano.sh
    resources:
      - modelroutes/status
      - modelservers/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
