//go:build !ignore_autogenerated

/*
Copyright MatrixInfer-AI Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicy) DeepCopyInto(out *AutoscalingPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicy.
func (in *AutoscalingPolicy) DeepCopy() *AutoscalingPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyBehavior) DeepCopyInto(out *AutoscalingPolicyBehavior) {
	*out = *in
	in.ScaleUp.DeepCopyInto(&out.ScaleUp)
	in.ScaleDown.DeepCopyInto(&out.ScaleDown)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyBehavior.
func (in *AutoscalingPolicyBehavior) DeepCopy() *AutoscalingPolicyBehavior {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyBehavior)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyList) DeepCopyInto(out *AutoscalingPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AutoscalingPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyList.
func (in *AutoscalingPolicyList) DeepCopy() *AutoscalingPolicyList {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AutoscalingPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyMetric) DeepCopyInto(out *AutoscalingPolicyMetric) {
	*out = *in
	out.TargetValue = in.TargetValue.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyMetric.
func (in *AutoscalingPolicyMetric) DeepCopy() *AutoscalingPolicyMetric {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyMetric)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyPanicPolicy) DeepCopyInto(out *AutoscalingPolicyPanicPolicy) {
	*out = *in
	if in.Percent != nil {
		in, out := &in.Percent, &out.Percent
		*out = new(int32)
		**out = **in
	}
	out.Period = in.Period
	if in.PanicThresholdPercent != nil {
		in, out := &in.PanicThresholdPercent, &out.PanicThresholdPercent
		*out = new(int32)
		**out = **in
	}
	if in.PanicModeHold != nil {
		in, out := &in.PanicModeHold, &out.PanicModeHold
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyPanicPolicy.
func (in *AutoscalingPolicyPanicPolicy) DeepCopy() *AutoscalingPolicyPanicPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyPanicPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyScaleUpPolicy) DeepCopyInto(out *AutoscalingPolicyScaleUpPolicy) {
	*out = *in
	in.StablePolicy.DeepCopyInto(&out.StablePolicy)
	in.PanicPolicy.DeepCopyInto(&out.PanicPolicy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyScaleUpPolicy.
func (in *AutoscalingPolicyScaleUpPolicy) DeepCopy() *AutoscalingPolicyScaleUpPolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyScaleUpPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicySpec) DeepCopyInto(out *AutoscalingPolicySpec) {
	*out = *in
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = make([]AutoscalingPolicyMetric, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Behavior.DeepCopyInto(&out.Behavior)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicySpec.
func (in *AutoscalingPolicySpec) DeepCopy() *AutoscalingPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyStablePolicy) DeepCopyInto(out *AutoscalingPolicyStablePolicy) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	if in.Percent != nil {
		in, out := &in.Percent, &out.Percent
		*out = new(int32)
		**out = **in
	}
	if in.Period != nil {
		in, out := &in.Period, &out.Period
		*out = new(v1.Duration)
		**out = **in
	}
	if in.StabilizationWindow != nil {
		in, out := &in.StabilizationWindow, &out.StabilizationWindow
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyStablePolicy.
func (in *AutoscalingPolicyStablePolicy) DeepCopy() *AutoscalingPolicyStablePolicy {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyStablePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AutoscalingPolicyStatus) DeepCopyInto(out *AutoscalingPolicyStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AutoscalingPolicyStatus.
func (in *AutoscalingPolicyStatus) DeepCopy() *AutoscalingPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AutoscalingPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoraAdapter) DeepCopyInto(out *LoraAdapter) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoraAdapter.
func (in *LoraAdapter) DeepCopy() *LoraAdapter {
	if in == nil {
		return nil
	}
	out := new(LoraAdapter)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Model) DeepCopyInto(out *Model) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Model.
func (in *Model) DeepCopy() *Model {
	if in == nil {
		return nil
	}
	out := new(Model)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Model) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelBackend) DeepCopyInto(out *ModelBackend) {
	*out = *in
	if in.EnvFrom != nil {
		in, out := &in.EnvFrom, &out.EnvFrom
		*out = make([]corev1.EnvFromSource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]corev1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ScaleToZeroGracePeriod != nil {
		in, out := &in.ScaleToZeroGracePeriod, &out.ScaleToZeroGracePeriod
		*out = new(v1.Duration)
		**out = **in
	}
	if in.Workers != nil {
		in, out := &in.Workers, &out.Workers
		*out = make([]ModelWorker, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LoraAdapters != nil {
		in, out := &in.LoraAdapters, &out.LoraAdapters
		*out = make([]LoraAdapter, len(*in))
		copy(*out, *in)
	}
	out.AutoscalingPolicyRef = in.AutoscalingPolicyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelBackend.
func (in *ModelBackend) DeepCopy() *ModelBackend {
	if in == nil {
		return nil
	}
	out := new(ModelBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelBackendStatus) DeepCopyInto(out *ModelBackendStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelBackendStatus.
func (in *ModelBackendStatus) DeepCopy() *ModelBackendStatus {
	if in == nil {
		return nil
	}
	out := new(ModelBackendStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelList) DeepCopyInto(out *ModelList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Model, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelList.
func (in *ModelList) DeepCopy() *ModelList {
	if in == nil {
		return nil
	}
	out := new(ModelList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ModelList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelSpec) DeepCopyInto(out *ModelSpec) {
	*out = *in
	if in.Backends != nil {
		in, out := &in.Backends, &out.Backends
		*out = make([]ModelBackend, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	out.AutoscalingPolicyRef = in.AutoscalingPolicyRef
	if in.CostExpansionRatePercent != nil {
		in, out := &in.CostExpansionRatePercent, &out.CostExpansionRatePercent
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelSpec.
func (in *ModelSpec) DeepCopy() *ModelSpec {
	if in == nil {
		return nil
	}
	out := new(ModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelStatus) DeepCopyInto(out *ModelStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BackendStatuses != nil {
		in, out := &in.BackendStatuses, &out.BackendStatuses
		*out = make([]ModelBackendStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelStatus.
func (in *ModelStatus) DeepCopy() *ModelStatus {
	if in == nil {
		return nil
	}
	out := new(ModelStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModelWorker) DeepCopyInto(out *ModelWorker) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
	in.Affinity.DeepCopyInto(&out.Affinity)
	in.Config.DeepCopyInto(&out.Config)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModelWorker.
func (in *ModelWorker) DeepCopy() *ModelWorker {
	if in == nil {
		return nil
	}
	out := new(ModelWorker)
	in.DeepCopyInto(out)
	return out
}
