apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kthena.name" . }}-infer-router-config
  namespace: {{ .Release.Namespace }}
data:
  routerConfiguration: |-
    scheduler:
      pluginConfig:
      - name: least-request
        args:
          maxWaitingRequests: 10
      - name: least-latency
        args:
          TTFTTPOTWeightFactor: 0.5
      - name: prefix-cache
        args:
          blockSizeToHash: 64
          maxBlocksToMatch: 128
          maxHashCacheSize: 50000
      - name: kvcache-aware
        args:
          blockSizeToHash: 128
          maxBlocksToMatch: 128
      plugins:
        Filter:
          enabled:
            - least-request
          disabled:
            - lora-affinity
        Score:
          enabled:
            - name: least-request
              weight: 1
            - name: gpu-usage
              weight: 1
            - name: least-latency
              weight: 1
            - name: prefix-cache
              weight: 1
