apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kthena.name" . }}-infer-router
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: infer-router
    {{- include "kthena.labels" . | nindent 4 }}
spec:
  replicas: {{.Values.inferRouter.replicas}}
  selector:
    matchLabels:
      app.kubernetes.io/component: infer-router
      {{- include "kthena.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: infer-router
        {{- include "kthena.labels" . | nindent 8 }}
    spec:
      containers:
        - name: infer-router
          image: "{{ .Values.inferRouter.image.repository }}:{{ .Values.inferRouter.image.tag }}"
          imagePullPolicy: {{ .Values.inferRouter.image.pullPolicy }}
          args:
            - --port={{ .Values.inferRouter.port }}
          {{- if and .Values.global.certManager.enabled .Values.inferRouter.tls.enabled }}
            - --tls-cert=/etc/tls/tls.crt
            - --tls-key=/etc/tls/tls.key
          {{- end }}
          ports:
            - containerPort: {{ .Values.inferRouter.port }}
              name: http
          env:
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_HOST
                  optional: true
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: REDIS_PORT
                  optional: true
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: password
                  optional: true
            # Fairness scheduling configuration
            - name: ENABLE_FAIRNESS_SCHEDULING
              value: {{ .Values.inferRouter.fairness.enabled | quote }}
            {{- if .Values.inferRouter.fairness.enabled }}
            - name: FAIRNESS_WINDOW_SIZE
              value: {{ .Values.inferRouter.fairness.windowSize | quote }}
            - name: FAIRNESS_INPUT_TOKEN_WEIGHT
              value: {{ .Values.inferRouter.fairness.inputTokenWeight | quote }}
            - name: FAIRNESS_OUTPUT_TOKEN_WEIGHT
              value: {{ .Values.inferRouter.fairness.outputTokenWeight | quote }}
            {{- end }}
            # Access log configuration
            - name: ACCESS_LOG_ENABLED
              value: {{ .Values.inferRouter.accessLog.enabled | quote }}
            - name: ACCESS_LOG_FORMAT
              value: {{ .Values.inferRouter.accessLog.format | quote }}
            - name: ACCESS_LOG_OUTPUT
              value: {{ .Values.inferRouter.accessLog.output | quote }}
          resources: {{- toYaml .Values.inferRouter.resource | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.inferRouter.port }}
              {{- if and .Values.global.certManager.enabled .Values.inferRouter.tls.enabled }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.inferRouter.port }}
              {{- if and .Values.global.certManager.enabled .Values.inferRouter.tls.enabled }}
              scheme: HTTPS
              {{- end }}
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
          - name: scheduler-config
            mountPath: /etc/config/routerConfiguration.yaml
            subPath: routerConfiguration
          {{- if and .Values.global.certManager.enabled .Values.inferRouter.tls.enabled }}
          - name: tls-certs
            mountPath: "/etc/tls"
            readOnly: true
          {{- end }}
      volumes:
        - name: scheduler-config
          configMap:
            name: {{ include "kthena.name" . }}-infer-router-config
        {{- if and .Values.global.certManager.enabled .Values.inferRouter.tls.enabled }}
        - name: tls-certs
          secret:
            secretName: {{ .Values.inferRouter.tls.secretName }}
        {{- end }}
      serviceAccountName:  {{ include "kthena.name" . }}-infer-router
