apiVersion: workload.matrixinfer.ai/v1alpha1
kind: modelinfer
metadata: ${MODEL_INFER_TEMPLATE_METADATA}
spec:
  recoveryPolicy: InferGroupRestart
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: InferGroupRollingUpdate
  schedulerName: volcano
  replicas: ${BACKEND_REPLICAS}
  template:
    restartGracePeriodSeconds: 60
    roles:
      - name: prefill
        replicas: ${PREFILL_REPLICAS}
        entryTemplate:
          spec:
            initContainers:
              - name: ${MODEL_NAME}-downloader
                imagePullPolicy: Always
                image: ${MODEL_INFER_DOWNLOADER_IMAGE}
                args:
                  - --source
                  - ${MODEL_URL}
                  - --output-dir
                  - ${MODEL_DOWNLOAD_PATH}
                envFrom: ${MODEL_DOWNLOAD_ENVFROM}
                volumeMounts: ${VOLUME_MOUNTS}
            containers:
              - name: runtime
                image: ${MODEL_INFER_RUNTIME_IMAGE}
                ports:
                  - containerPort: 8100
                args:
                  - --port
                  - ${MODEL_INFER_RUNTIME_PORT}
                  - --url
                  - ${MODEL_INFER_RUNTIME_URL}
                  - --engine
                  - ${MODEL_INFER_RUNTIME_ENGINE}
              - name: vllm
                image: ${ENGINE_PREFILL_IMAGE}
                ports:
                  - containerPort: 8000
                env:
                  - name: HF_HUB_OFFLINE
                    value: "1"
                  - name: HCCL_IF_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: GLOO_SOCKET_IFNAME
                    value: eth0
                  - name: TP_SOCKET_IFNAME
                    value: eth0
                  - name: HCCL_SOCKET_IFNAME
                    value: eth0
                command: ${ENGINE_PREFILL_COMMAND}
                imagePullPolicy: IfNotPresent
                resources: ${ENGINE_PREFILL_RESOURCES}
                readinessProbe:
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                livenessProbe:
                  initialDelaySeconds: 900
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                volumeMounts: ${VOLUME_MOUNTS}
            volumes: ${VOLUMES}
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: volcano.sh/hypernode
                          operator: In
                          values:
                            - 78533445-4b1f-11f0-a3ab-0255ac10007d
        workerReplicas: 0
        workerTemplate:
          spec:
            containers: []
      - name: decode
        replicas: ${DECODE_REPLICAS}
        entryTemplate:
          spec:
            initContainers:
              - name: downloader
                imagePullPolicy: Always
                image: ${MODEL_INFER_DOWNLOADER_IMAGE}
                args:
                  - --source
                  - ${MODEL_URL}
                  - --output-dir
                  - ${MODEL_DOWNLOAD_PATH}
                envFrom: ${MODEL_DOWNLOAD_ENVFROM}
                volumeMounts: ${VOLUME_MOUNTS}
            containers:
              - name: runtime
                image: ${MODEL_INFER_RUNTIME_IMAGE}
                ports:
                  - containerPort: 8100
                args:
                  - --port
                  - ${MODEL_INFER_RUNTIME_PORT}
                  - --url
                  - ${MODEL_INFER_RUNTIME_URL}
                  - --engine
                  - ${MODEL_INFER_RUNTIME_ENGINE}
              - name: vllm
                image: ${ENGINE_DECODE_IMAGE}
                ports:
                  - containerPort: 8000
                env:
                  - name: HF_HUB_OFFLINE
                    value: "1"
                  - name: GLOO_SOCKET_IFNAME
                    value: eth0
                  - name: TP_SOCKET_IFNAME
                    value: eth0
                  - name: HCCL_SOCKET_IFNAME
                    value: eth0
                command: ${ENGINE_DECODE_COMMAND}
                imagePullPolicy: IfNotPresent
                resources: ${ENGINE_DECODE_RESOURCES}
                readinessProbe:
                  initialDelaySeconds: 5
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                livenessProbe:
                  initialDelaySeconds: 900
                  periodSeconds: 5
                  failureThreshold: 3
                  httpGet:
                    path: /health
                    port: 8000
                volumeMounts: ${VOLUME_MOUNTS}
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: volcano.sh/hypernode
                          operator: In
                          values:
                            - f0189bcc-1479-11f0-8512-0255ac100079
            volumes: ${VOLUMES}
        workerReplicas: 0
        workerTemplate:
          spec:
            containers: []