name: Docker Push
on:
  workflow_dispatch: # manual trigger
  push:
    branches:
      - main
    paths:
      - '**.go'
      - "pkg/**"
      - "cmd/**"
      - "go.mod"
      - "go.sum"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'matrixinfer-ai/matrixinfer'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # push to ghcr.io when merged to main.
      - name: Log in to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        run: make docker-buildx
