name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/kthena/**'

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '24.5.0'
          cache: npm
          cache-dependency-path: ./docs/kthena/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs/kthena
      - name: Build website
        run: npm run build
        working-directory: ./docs/kthena

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/kthena/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4