name: E2E Tests

on:
  workflow_dispatch:
  # Uncomment the following lines to enable E2E tests on pull requests to main branch
  # It will 100% failed because not enough memory in GitHub-hosted runners
#  pull_request:
#    branches:
#      - main
#    paths:
#      - '**.go'
#      - "pkg/**"
#      - "cmd/**"
#      - "test/e2e/**"
#      - "go.mod"
#      - "go.sum"
#      - "Makefile"
#      - "charts/matrixinfer/charts/*/crds/*.yaml"

jobs:
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Install helm
        shell: bash
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        with:
          install_only: true # Skips cluster creation, only install kind
      - name: Run E2E Tests
        run: make test-e2e
        env:
          CLUSTER_NAME: matrixinfer-e2e-ci # Create a cluster named matrixinfer-e2e-ci, then run tests in it
      - name: Cleanup E2E Environment
        if: always()
        run: make test-e2e-cleanup
        env:
          CLUSTER_NAME: matrixinfer-e2e-ci
      - name: Collect logs on failure
        if: failure()
        run: |
          echo "=== Kind cluster logs ==="
          if kind get clusters | grep -q matrixinfer-e2e-ci; then
            kind export logs --name matrixinfer-e2e-ci /tmp/kind-logs || true
            echo "Logs exported to /tmp/kind-logs"
            ls -la /tmp/kind-logs/ || true
          fi
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-logs
          path: /tmp/kind-logs/
          retention-days: 7
