# removing the lgtm label when a PR is updated
name: Remove LGTM Label on PR Update
on: pull_request

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: jpmcb/prow-github-actions@v2
        with:
          jobs: lgtm
          github-token: '${{ secrets.PROW_TOKEN }}'